apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: demo
spec:
  allocatedStorage: 
  autoMinorVersionUpgrade: true
  backupRetentionPeriod: 7
  dbInstanceClass: 
  dbInstanceIdentifier: 
  dbName: demo
  dbSubnetGroupName: 
  enablePerformanceInsights: true
  engine: postgres
  engineVersion: "13"
  masterUsername: 
  masterUserPassword:
    namespace: 
    name: demo-postgres-creds
    key: password
  multiAZ: true
  publiclyAccessible: false
  storageEncrypted: true
  storageType: gp2
  vpcSecurityGroupIDs:
    - EKS_VPC_ID
