name: Policy

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:

  policy:
    uses: example-policy-org/policy-action/.github/workflows/ci.yml@main