name: Policy

on:
  push:
  pull_request:

jobs:

  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: docker://ghcr.io/example-policy-org/policy-checker:latest

